### ISSUE TITLE
polymer-3-sandbox does not work in Firefox

### ISSUE THREAD

**Issue by ergo** [katejeffreys-projects/polymer-3-sandbox#7]
Hi Kate,

Thank you for this project, I know polymer is a chrome project and all but I think it would be great if the page would be also working in Firefox, maybe some start events are not being fired?

**Comment by katejeffreys** [comment]
There were a couple of bugs, but also Firefox has es6 modules behind a flag. 

I can probably get it working in firefox nightly pretty soon 

https://github.com/katejeffreys-projects/polymer-3-sandbox/tree/firefox

**Comment by katejeffreys** [comment]
Works in firefox nightly, or in v 54-60 with `dom.moduleScripts.enabled`

**Comment by ergo** [comment]
@katejeffreys you are glorious for solving this, thanks. Is there a polyfill one can use to get it working for everyone right now though, without changing configs?
